/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'content' : string,
  'authorName' : string,
  'timestamp' : Time,
}
export interface ContactEntry {
  'principal' : Principal,
  'profile' : UserProfile,
}
export interface GroupEntry { 'id' : string, 'group' : GroupSnapshot }
export interface GroupMessage {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'senderName' : string,
}
export interface GroupSnapshot {
  'id' : string,
  'members' : Array<Principal>,
  'name' : string,
  'department' : string,
}
export interface Message {
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type Role = { 'admin' : null } |
  { 'faculty' : null } |
  { 'student' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'isOnline' : boolean,
  'email' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[Announcement], undefined>,
  'createGroup' : ActorMethod<[string, string], string>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<ContactEntry>>,
  'getGroupMessages' : ActorMethod<[string], Array<GroupMessage>>,
  'getGroups' : ActorMethod<[], Array<GroupEntry>>,
  'getMessageHistory' : ActorMethod<[Principal], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendGroupMessage' : ActorMethod<[string, string], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'updateDepartment' : ActorMethod<[Principal, string], undefined>,
  'updateRole' : ActorMethod<[Principal, Role], undefined>,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];