/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : Time,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'faculty' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'isOnline' : IDL.Bool,
  'email' : IDL.Text,
  'department' : IDL.Text,
});
export const ContactEntry = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
});
export const GroupMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'senderName' : IDL.Text,
});
export const GroupSnapshot = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'department' : IDL.Text,
});
export const GroupEntry = IDL.Record({
  'id' : IDL.Text,
  'group' : GroupSnapshot,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([Announcement], [], []),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(ContactEntry)], ['query']),
  'getGroupMessages' : IDL.Func([IDL.Text], [IDL.Vec(GroupMessage)], ['query']),
  'getGroups' : IDL.Func([], [IDL.Vec(GroupEntry)], ['query']),
  'getMessageHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateDepartment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'updateRole' : IDL.Func([IDL.Principal, Role], [], []),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : Time,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'faculty' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'isOnline' : IDL.Bool,
    'email' : IDL.Text,
    'department' : IDL.Text,
  });
  const ContactEntry = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
  });
  const GroupMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'senderName' : IDL.Text,
  });
  const GroupSnapshot = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'department' : IDL.Text,
  });
  const GroupEntry = IDL.Record({ 'id' : IDL.Text, 'group' : GroupSnapshot });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([Announcement], [], []),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(ContactEntry)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getGroups' : IDL.Func([], [IDL.Vec(GroupEntry)], ['query']),
    'getMessageHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendGroupMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateDepartment' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'updateRole' : IDL.Func([IDL.Principal, Role], [], []),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };